#!/bin/bash

## Description: run mysqldump-root in web container
## Usage: mysqldump-root [flags] [args]
## Example: "ddev mysqldump-root db" or "ddev mysqldump-root otherdb" or "ddev mysqldump-root db | gzip >db.sql.gz"

mysqldump -uroot -proot $@
