#!/bin/bash

## #ddev-generated
## Description: run mysql client in db container
## Usage: mysql-root [flags] [args]
## Example: "ddev mysql-root" or "echo 'SHOW TABLES;' | ddev mysql-root"
## `ddev mysql-root --database=mysql` gets you to the 'mysql' database with root privileges

mysql -uroot -proot $@
