#!/bin/bash

## Description: cleanup all the things

ddev remove --remove-data

rm -fR var/
rm -fR vendor/
rm -fR public/fileadmin
rm -fR public/typo3
rm -fR public/typo3temp
rm -fR public/typo3conf/ext
rm -fR public/typo3conf/l10n


rm -fR public/typo3conf/LocalConfiguration.php
rm -fR public/typo3conf/PackageStates.php
rm -fR public/index.php



