#!/bin/bash

## Description: cleanup all the things

ddev delete --omit-snapshot --yes

# Remove following file to be able to import the not covered by impexp data as SQL again.
rm -fr packages/*/Initialisation/not_covered_by_impexp.isImported

rm -fR var/
rm -fR vendor/
rm -fR public/fileadmin
rm -fR public/typo3
rm -fR public/typo3temp
rm -fR public/typo3conf/ext
rm -fR public/typo3conf/l10n

rm -fR public/typo3conf/LocalConfiguration.php
rm -fR public/typo3conf/PackageStates.php
rm -fR public/index.php

rm -fR .ddev/solr/site
rm -fR .ddev/solr/tests


