#!/bin/bash

## Description: clones EXT:solr repository into packages/ folder


if [ ! -d "packages/ext-solr" ];then
  git clone git@github.com:TYPO3-Solr/ext-solr.git packages/ext-solr;
else
  echo "EXT:solr repo presents in packages/ext-solr."
  echo "If needed, checkout the desired ext-solr branch and update composer by your self."
  exit 0; # Don't checkout something on ddev restarts
fi

current_ddev_site_branch=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

previous_pwd=$PWD
cd 'packages/ext-solr'

if [ "$(git branch --list "$current_ddev_site_branch")" ] ; then
   echo "Checking out ext-solr \"$current_ddev_site_branch\" as on solr-ddev-site repository."
   git checkout "$current_ddev_site_branch"
else
  echo "The branch $current_ddev_site_branch does not exist on ext-solr, leaving in $(git rev-parse --symbolic-full-name --abbrev-ref HEAD)"
fi

cd $previous_pwd

