#!/bin/bash

## Description: Enables the EXT:Solr* plugin (Note: EB EXT:Solr plugins must exist in packages/ext-<solr-plugin-name>)
## Usage: solr:disable <solr-plugin-name>
## Example: ddev solr:disable solrfal \nddev solr:disable solrdebugtools \nddev solr:disable solrfluidgrouping \nddev solr:disable news



EXT_NAME=$1
LOCAL_EXT_SOLR_PLUGIN_PATH="packages/ext-$EXT_NAME"

RED='\033[0;31m'
NC='\033[0m'

if [[ ! -d "packages/introduction_""$EXT_NAME" ]]; then
  echo "The integration for $EXT_NAME extension does not exists."
  echo "Please provide a pull request for this extension by adding a extension like https://github.com/TYPO3-Solr/solr-ddev-site/tree/c313aaecd8b63fe3b3a0956d052a444de18517be/packages/introduction_news"
  exit 1;
fi


LOCAL_EXT_SOLR_PLUGIN=""
if [[ -d "$LOCAL_EXT_SOLR_PLUGIN_PATH"  ]]; then
  LOCAL_EXT_SOLR_PLUGIN="apache-solr-for-typo3/$EXT_NAME"
fi

echo "Uninstalling $LOCAL_EXT_SOLR_PLUGIN"
# shellcheck disable=SC2086
if ! ddev composer remove "apache-solr-for-typo3/introduction-$EXT_NAME" $LOCAL_EXT_SOLR_PLUGIN ; then
  EXECUTED_COMMAND="composer remove \"apache-solr-for-typo3/introduction-$EXT_NAME\" $LOCAL_EXT_SOLR_PLUGIN"
  echo "Something went wrong by following composer command:"
  echo "    $EXECUTED_COMMAND"
  echo "please check the output from above."
  exit 1;
fi

BELONGING_DOCKER_COMPOSE_SERVICE_FILE="./packages/introduction_$EXT_NAME/docker-compose.$EXT_NAME.yaml"
if [[ -f "$BELONGING_DOCKER_COMPOSE_SERVICE_FILE" ]] && [[ -f ".ddev/docker-compose.$EXT_NAME.yaml" ]]; then
  rm ".ddev/docker-compose.$EXT_NAME.yaml"
  echo -e "\n${RED}The EXT:$EXT_NAME introduced the additional Docker service. The ddev will be restarted to remove the services for EXT:$EXT_NAME.${NC}\n"
  ddev restart
fi
