#!/bin/bash

## Description: Cleanup all the things to be able to start clean and default state
## Usage: solr:clean:ddev-site

ddev delete --omit-snapshot --yes

echo "Removing transient files in project."
# Remove following file to be able to import the not covered by impexp data as SQL again.
rm -fv packages/*/Initialisation/not_covered_by_impexp.isImported

rm -fR var/
rm -fR vendor/
rm -fR public/fileadmin
rm -fR public/typo3
rm -fR public/typo3temp
rm -fR public/typo3conf/ext
rm -fR public/typo3conf/l10n

rm -fv public/typo3conf/LocalConfiguration.php
rm -fv public/typo3conf/PackageStates.php
rm -fv public/index.php

rm -fR .ddev/solr/site
rm -fR .ddev/solr/tests

echo "Restoring composers original state."
git checkout composer.json composer.lock
