#!/bin/bash

## Description: run unit tests in web container

UNIT_BOOTSTRAP="public/typo3conf/ext/solr/Build/Test/UnitTestsBootstrap.php"
UNIT_CONFIGURATION="public/typo3conf/ext/solrconsole/Build/Test/UnitTests.xml"

./vendor/bin/phpunit \
  --bootstrap=$UNIT_BOOTSTRAP \
  --configuration $UNIT_CONFIGURATION \
  --colors "$@"
