#!/bin/bash

## Description: run unit tests in web container

UNIT_BOOTSTRAP="vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php"
UNIT_CONFIGURATION="public/typo3conf/ext/solrfal/Build/Test/UnitTests.xml"

./vendor/bin/phpunit \
  --bootstrap=$UNIT_BOOTSTRAP \
  --configuration $UNIT_CONFIGURATION \
  --colors "$@"
