#!/bin/bash

## Description: run unit tests in web container (don't forget to run `ddev composer-update--lock` if ext-solr*'s composer.json changed)

UNIT_BOOTSTRAP="vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php"
SOLR_UNIT_TESTS_PATH="public/typo3conf/ext/tika/Build/Test/UnitTests.xml"

./vendor/bin/phpunit --colors -c $SOLR_UNIT_TESTS_PATH --bootstrap=$UNIT_BOOTSTRAP $@
