#!/bin/bash

## Description: run unit tests for EXT:solr stack
## Usage: solr:tests:unit [EXT:name] [--] [phpunit-args]
## Example: ddev solr:tests:unit                           # will run unit tests for all enabled extensions\nddev solr:tests:unit solr                      # will run unit tests for EXT:solr only\nddev solr:tests:unit solr --filter=ItemTest    # will run unit tests for EXT:solr's Unit\IndexQueue\ItemTest

function expandAllSolrExtensions() {
  local solrExtensions=(
    public/typo3conf/ext/solr*
    public/typo3conf/ext/tika
  )
  echo "${solrExtensions[@]}"
}

function checkExtensionIsInstalled() {
  if [[ ! -d "$1" ]]; then
    >&2 echo -e "EXT:$(basename "$1") is not enabled. Please enable it by:\n"
    >&2 echo -e "ddev solr:enable $(basename "$1")\n"
    exit 24
  fi
}

FIRST_LINE_PREFIX=""
function runUnitTests() {
  checkExtensionIsInstalled "$1"
  echo -e "${FIRST_LINE_PREFIX}Run Unit tests on EXT:$(basename "$1")\n\n"
  UNIT_CONFIGURATION="$1/Build/Test/UnitTests.xml"
  UNIT_BOOTSTRAP="packages/ext-solr/Build/Test/UnitTestsBootstrap.php"
  ./vendor/bin/phpunit \
    --bootstrap="${UNIT_BOOTSTRAP}" \
    --configuration "${UNIT_CONFIGURATION}" \
    --colors "${@:2}"
}

if [[ "$#" -eq 0 ]] || [[ "$1" == "all" ]]; then
  for solrExtension in $(expandAllSolrExtensions)
  do
    if [[ ! -d "${solrExtension}" ]]; then continue; fi
    runUnitTests "${solrExtension}" "${@:2}"
    FIRST_LINE_PREFIX="\n\n\n"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
    echo ""
  done
  exit 0
fi

runUnitTests "packages/ext-$1" "${@:2}"
