#!/bin/bash

## Description: run unit tests in web container

cd packages/.Test-Build/
UNIT_BOOTSTRAP="vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php"
SOLR_UNIT_TESTS_PATH="public/typo3conf/ext/solr/Build/Test/UnitTests.xml"

bin/phpunit --colors -c $SOLR_UNIT_TESTS_PATH --bootstrap=$UNIT_BOOTSTRAP $@
