#!/bin/bash

## Description: run integration tests for EXT:solr stack
## Usage: solr:tests:integration [EXT:name] [--] [phpunit-args]
## Example: ddev solr:tests:integration                           # will run integration tests for all enabled extensions\nddev solr:tests:integration solr                      # will run integration tests for EXT:solr only\nddev solr:tests:integration solr --filter=IndexerTest    # will run integration tests for EXT:solr's Integration\IndexQueue\IndexerTest

function expandAllSolrExtensions() {
  local solrExtensions=(
    public/typo3conf/ext/solr*
    public/typo3conf/ext/tika
  )
  echo "${solrExtensions[@]}"
}

function checkExtensionIsInstalled() {
  if [[ ! -d "$1" ]]; then
    >&2 echo -e "EXT:$(basename "$1") is not enabled. Please enable it by:\n"
    >&2 echo -e "ddev solr:enable $(basename "$1")\n"
    exit 24
  fi
}

FIRST_LINE_PREFIX=""
function runIntegrationTests() {
  checkExtensionIsInstalled "$1"
  echo -e "${FIRST_LINE_PREFIX}Run Integration tests on EXT:$(basename "$1")\n\n"
  INTEGRATION_CONFIGURATION="$1/Build/Test/IntegrationTests.xml"
  INTEGRATION_BOOTSTRAP="$1/Build/Test/IntegrationTestsBootstrap.php"
  ./vendor/bin/phpunit \
    --bootstrap="${INTEGRATION_BOOTSTRAP}" \
    --configuration "${INTEGRATION_CONFIGURATION}" \
    --colors "${@:2}"
}

if [[ "$#" -eq 0 ]] || [[ "$1" == "all" ]]; then
  for solrExtension in $(expandAllSolrExtensions)
  do
    if [[ ! -d "${solrExtension}" ]]; then continue; fi
    runIntegrationTests "${solrExtension}" "${@:2}"
    FIRST_LINE_PREFIX="\n\n\n"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
    echo ""
  done
  exit 0
fi

runIntegrationTests "packages/ext-$1" "${@:2}"
