#!/bin/bash

## Description: run unit tests in web container (don't forget to run `ddev composer-update--lock` if ext-solr*'s composer.json changed)

UNIT_BOOTSTRAP="vendor/nimut/testing-framework/res/Configuration/UnitTestsBootstrap.php"
UNIT_CONFIGURATION="public/typo3conf/ext/solrmlt/Build/Test/UnitTests.xml"

./vendor/bin/phpunit \
  --bootstrap=$UNIT_BOOTSTRAP \
  --configuration $UNIT_CONFIGURATION \
  --colors "$@"
