#!/bin/bash

## Description: run unit tests in web container (don't forget to run `ddev composer-update--lock` if ext-solr*'s composer.json changed)

UNIT_BOOTSTRAP="packages/ext-solr/Build/Test/UnitTestsBootstrap.php"
UNIT_CONFIGURATION="packages/ext-solr/Build/Test/UnitTests.xml"

./vendor/bin/phpunit \
  --bootstrap=$UNIT_BOOTSTRAP \
  --configuration $UNIT_CONFIGURATION \
  --colors "$@"

--bootstrap=packages/ext-solr/Build/Test/UnitTestsBootstrap.php --configuration packages/ext-solr/Build/Test/UnitTests.xml --colors
